language: node_js
cache: yarn
install:
  - yarn
jobs:
  include:
    - stage: lint
      script:
        - yarn lint .
    - stage: test
      script:
        - yarn test
    - stage: build
      script:
        - yarn build
    - stage: deploy
      if: branch = master
      after_install:
        - yarn global add firebase-tools
      before_script:
        - firebase use "$FIREBASE_PROJECT_ID"
      script:
        - firebase deploy --token "$FIREBASE_TOKEN"
